name: Deploy Frontend Centac (Develop)

on:
  push:
    branches:
      - develop

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Descargar el código
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23 
          cache: 'npm'     # Esto acelera futuros despliegues

      - name: 3. Instalar y Construir
        run: |
          npm ci           # 'npm ci' es más estricto y rápido para CI que 'npm install'
          npm run build

      - name: 4. Validar existencia de carpeta dist
        run: ls -la dist/  # Esto nos dirá en los logs si la carpeta realmente se creó

      - name: 5. Desplegar archivos al VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "dist/*"
          target: "/var/www/centac.co"
          strip_components: 1